### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by DjoCoding** [DjoCoding/packl#31]
Im thinking about making PACKL support classes only, that means, replace the records to classes, and add the implementation of the class methods outside the class definition, here's an example:

class Node {
   value: int;
   next: ptr;
};

func Node.init(value: int): Node {
    var node: Node = new Node;
    node.value = value;
    node.next = 0;
    init = node;
}

proc main() {
   var head: Node;
   head.init(10);
   exit(0);
}

...

**Comment by Djaoued2006** [comment]
about the data structure for the compiler, i can add to the compiler context, a new context item type, which is the Class item, that, it's a dynamic array of classes, each class item context, contains a dynamic array of methods and attributes, a method is defined by it's name, label value, and an attribute is defined by it's name, it's offset from the object pointer.
